services:
  api-1:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/henrich-m/rinha-de-backend-2026:v2
    command: bundle exec iodine -b /run/api/api.sock -t 1 -w 0
    environment:
      KNN_NPROBE: "8"
      NO_SSL: 1
      MALLOC_ARENA_MAX: "2"
    volumes:
      - api1_socket:/run/api
    deploy:
      resources:
        limits:
          memory: 170MB
          cpus: 0.4

  api-2:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/henrich-m/rinha-de-backend-2026:v2
    command: bundle exec iodine -b /run/api/api.sock -t 1 -w 0
    environment:
      KNN_NPROBE: "8"
      MALLOC_ARENA_MAX: "2"
      NO_SSL: 1
    volumes:
      - api2_socket:/run/api
    deploy:
      resources:
        limits:
          memory: 170MB
          cpus: 0.4

  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - api1_socket:/run/api1
      - api2_socket:/run/api2
    deploy:
      resources:
        limits:
          memory: 10MB
          cpus: 0.2

  trainer:
    profiles: [build]
    build:
      context: ./api
      dockerfile: Dockerfile.trainer
    volumes:
      - ./api:/app

volumes:
  api1_socket:
  api2_socket:
