services:
  db:
    image: pgvector/pgvector:pg18
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rinha"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "9999:9999"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/rinha
    depends_on:
      db:
        condition: service_healthy
    command: bundle exec falcon serve --bind http://0.0.0.0:9999

volumes:
  bundle_cache:
