# frozen_string_literal: true

source "https://rubygems.org"

gem "falcon"
gem "io-endpoint"
gem "roda"
gem "numo-narray"
gem "faiss"
gem "oj"  # used by knn_trainer.rb during the build stage

group :test do
  gem "minitest"
  gem "rake"
end
