worker_processes 1;

events {
  worker_connections 512;
}

http {
  access_log off;

  upstream api {
    server unix:/sockets/api-1/api.sock;
    server unix:/sockets/api-2/api.sock;
    keepalive 32;
  }

  server {
    listen 9999;

    location / {
      proxy_pass         http://api;
      proxy_http_version 1.1;
      proxy_set_header   Connection "";
      proxy_next_upstream error timeout http_502 http_503;
    }
  }
}
